spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: MS-ACCOUNT
              uri: lb://ms-account
              predicates:
                - Path=/api/account/**
              filters:
                - StripPrefix=2


            - id: ms-bill
              uri: lb://ms-bill
              predicates:
                - Path=/api/bill/**
              filters:
                - StripPrefix=2


            - id: ms-payment
              uri: lb://ms-payment
              predicates:
                - Path=/api/payment/**
              filters:
                - StripPrefix=2

            - id: ms-ocr
              uri: lb://MS-BILL-OCR
              predicates:
                - Path=/api/ocr/**
              filters:
                - RewritePath=/api/ocr/(?<segment>.*), /api/bill/$\{segment}

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}